signaling/room/__init__.py
from flask import Blueprint

room = Blueprint('room', __name__, template_folder="templates")

from . import routes

signaling/room/routes.py
from . import room
from uuid import uuid4
from flask import request, render_template, redirect, url_for, session


@room.route('/', methods=['GET', 'POST'])
def index():
    room_id = request.args.get('room_id')
    if room_id is not None:
        session['roomId'] = room_id
        if request.method == 'POST':
            username = request.form.get('username')
            session['username'] = username
            print('set username:', session.get('username'))
        return render_template('room/video-call.html', room_id=room_id)
    return render_template('room/index.html')


@room.route('/generate-room', methods=['POST'])
def generate_room():
    room_id = uuid4()
    return redirect(url_for('room.index', room_id=room_id))

signaling/room/templates/room/index.html
{% extends 'base.html' %}
{% block title %}Room{% endblock %}
{% block head %}
    {{ super() }}
    <style type="text/css">
    </style>
{% endblock %}
{% block content %}
    <h2>Index</h2>
    <div>
        <form method="POST" id="generate-room" action="{{ url_for('room.generate_room') }}">
            <input type="submit" value="Start Video Call">
        </form>
    </div>
{% endblock %}
{% block footer %}
{{ super() }}
<script type="text/javascript" src="{{ url_for('static', filename='js/room.js') }}"></script>
{% endblock %}

signaling/room/templates/room/video-call.html
{% extends 'base.html' %}
{% block title %}Room{% endblock %}
{% block head %}
    {{ super() }}
    <style type="text/css">
    </style>
{% endblock %}
{% block content %}
<div id="vm">
    <h2>Video Call</h2>
    <div>
        <span>Room ID: </span> <strong>{{ room_id }}</strong>
    </div>
    <form v-if="!username" method="post" action="{{ url_for('room.index', room_id=room_id) }}">
        <input name="username" type="text">
        <input type="submit" value="Submit">
    </form>
    <video v-if="remoteStream" class="remoteStream" :src-object.prop.camel="remoteStream" autoplay></video>
    <video v-if="localStream" class="localStream" :src-object.prop.camel="localStream" autoplay muted></video>
    <button class="" v-on:click="toggleVoice">
        <span v-if="isVoiceOn">turn off voice</span>
        <span v-else>turn on voice</span>
    </button>
    <button class="" v-on:click="toggleCamera">
        <span v-if="isCameraOn">turn off camera</span>
        <span v-else>turn on camera</span>
    </button>
</div>
{% endblock %}
{% block footer %}
{{ super() }}
<script type="text/javascript" src="{{ url_for('static', filename='vendors/vue-socket.io/dist/vue-socketio.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='vendors/store2/dist/store2.min.js') }}"></script>
<script type="module" src="{{ url_for('static', filename='js/room.js') }}"></script>
{% endblock %}