signaling/user/__init__.py
from flask import Blueprint

user = Blueprint('user', __name__, template_folder="../user/templates")

from . import routes

signaling/user/routes.py
from . import user
from flask import render_template


@user.route('/', methods=['GET'])
def index():
    return render_template('user/index.html')


@user.route('/signin', methods=['GET', 'POST'])
def signin():
    return render_template('user/signin.html')


@user.route('/register', methods=['GET', 'POST'])
def register():
    return render_template('user/register.html')

signaling/user/templates/user/index.html
{% extends 'base.html' %}
{% block title %}User{% endblock %}
{% block head %}
    {{ super() }}
    <style type="text/css">
    </style>
{% endblock %}
{% block content %}
<h2>User Profile</h2>
{% endblock %}
{% block footer %}
{{ super() }}
<script type="text/javascript" src="{{ url_for('static', filename='js/user.js') }}"></script>
{% endblock %}

signaling/user/templates/user/register.html
{% extends 'base.html' %}
{% block title %}User{% endblock %}
{% block head %}
<h2>Register</h2>
<div>
    <form action="{{ url_for('user.register') }}" method="POST">
        <div class="form-group">
            <label for="username">Username</label>
            <input type="text" name="username">
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" name="password">
        </div>
        <div class="form-group">
            <label for="confirm-password">Confirm Password</label>
            <input type="password" name="confirm-password">
        </div>
        <div class="form-group">
            <label for="fistname">Firstname</label>
            <input type="text" name="firstname">
        </div>
        <div class="form-group">
            <label for="lastname">Lastname</label>
            <input type="lastname" name="lastname">
        </div>
        <input type="submit" value="Register">
    </form>
</div>
{% endblock %}
{% block footer %}
{{ super() }}
<script type="text/javascript" src="{{ url_for('static', filename='js/user.js') }}"></script>
{% endblock %}

signaling/user/templates/user/signin.html
{% extends 'base.html' %}
{% block title %}User{% endblock %}
{% block head %}
<h2>Signin</h2>
<div>
    <form method="POST" action="{{ url_for('user.signin') }}">
        <div class="form-group">
            <label for="username">Username</label>
            <input type="text" name="username">
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" name="password">
        </div>
        <input type="submit" value="signin">
    </form>
</div>
{% endblock %}
{% block footer %}
{{ super() }}
<script type="text/javascript" src="{{ url_for('static', filename='js/user.js') }}"></script>
{% endblock %}